# Stage 1
FROM node:20 AS BASE
WORKDIR /app
COPY package*.json /app
RUN npm install
COPY . .

# Stage 2
FROM node:20-alpine3.20
WORKDIR /app
COPY --from=BASE /app .

EXPOSE 5173
ENTRYPOINT ["npm", "run", "dev", "--", "--host"]